# -*- coding: utf-8 -*-
"""Proyek Analisis Data - Ridwan Donovan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uX4wnPEMM0Mq1_nEZGTuoCD3csX6RiO7

# Proyek Analisis Data: [Bike Sharing Dataset]
- **Nama:** [Ridwan Donovan]
- **Email:** [donostdy@gmail.com]
- **ID Dicoding:** [ridwandonovan]

## Menentukan Pertanyaan Bisnis

```
# This is formatted as code
```

- Korelasi antara kondisi cuaca dengan jumlah persewaan?
- Bagaimana perbandingan jumlah persewaan antara hari libur dan hari kerja?
- Bagaimana perkembangan persewaan sepeda dari tahun 2011 sampai 2012?

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

link = "https://raw.githubusercontent.com/donostdy/Bike-Sharing-Data-Analysis/main/day.csv"

df = pd.read_csv(link)
df.head()

"""### Assessing Data"""

df.info()

df.isna().sum()

print("Jumlah duplikasi: ", df.duplicated().sum())

"""### Cleaning Data

Dari pengecekan data diatas, tidaka ada data duplikat, maupun null

## Exploratory Data Analysis (EDA)

### Explore ...
"""

df.describe()

"""## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

# Group by 'weathersit' and calculate the mean 'cnt' for each group
weather_cnt_means = df.groupby('weathersit')['cnt'].mean().reset_index()

# Map weathersit values to corresponding labels using the attribute information
weather_labels = {
    1: 'Clear, Few clouds',
    2: 'Mist + Cloudy',
    3: 'Light Snow, Light Rain',
    4: 'Heavy Rain + Thunderstorm + Mist, Snow + Fog'
}

# Add a new column with weather labels
weather_cnt_means['weathersit_label'] = weather_cnt_means['weathersit'].map(weather_labels)

# Define custom colors
custom_palette = {'Clear, Few clouds': 'red', 'Mist + Cloudy': 'grey', 'Light Snow, Light Rain': 'grey', 'Heavy Rain + Thunderstorm + Mist, Snow + Fog': 'grey'}

# Plot the bar plot with custom colors
plt.figure(figsize=(10, 6))
sns.barplot(x='weathersit_label', y='cnt', data=weather_cnt_means, palette=custom_palette)
plt.title('Average Count of Rental Bikes for Each Weather Situation')
plt.xlabel('Weather Situation')
plt.ylabel('Average Count of Rental Bikes')
plt.show()

"""### Pertanyaan 2:"""

# Group by 'workingday' and calculate the mean 'cnt' for each group
workingday_cnt_means = df.groupby('workingday')['cnt'].mean().reset_index()

# Map workingday values to corresponding labels using the attribute information
workingday_labels = {0: 'Weekend/Holiday', 1: 'Working Day'}

# Add a new column with workingday labels
workingday_cnt_means['workingday_label'] = workingday_cnt_means['workingday'].map(workingday_labels)

# Define custom colors
custom_palette = {'Working Day': 'red', 'Weekend/Holiday': 'grey'}

# Plot the bar plot with custom colors
plt.figure(figsize=(8, 5))
sns.barplot(x='workingday_label', y='cnt', data=workingday_cnt_means, palette=custom_palette)
plt.title('Average Count of Rental Bikes for Working Day vs. Weekend/Holiday')
plt.xlabel('Day Type')
plt.ylabel('Average Count of Rental Bikes')
plt.show()

# Convert 'dteday' to datetime type if it's not already
df['dteday'] = pd.to_datetime(df['dteday'])

# Group by 'yr' and 'dteday' and calculate the sum 'cnt' for each group
yearly_cnt_sum = df.groupby(['yr', 'dteday'])['cnt'].sum().reset_index()

# Map yr values to corresponding labels using the attribute information
year_labels = {0: 2011, 1: 2012}

# Add a new column with year labels
yearly_cnt_sum['year_label'] = yearly_cnt_sum['yr'].map(year_labels)

# Define custom colors
custom_palette = {2011: 'grey', 2012: 'red'}

# Plot the line chart with custom colors
plt.figure(figsize=(12, 6))
sns.lineplot(x='dteday', y='cnt', hue='year_label', data=yearly_cnt_sum, palette=custom_palette)
plt.title('Count of Rental Bikes Over the Year')
plt.xlabel('Date')
plt.ylabel('Count of Rental Bikes')
plt.legend(title='Year')
plt.show()

"""## Conclusion

- Conclution pertanyaan 1: Dapat dilihat bahwa penyewaan sepeda paling banyak pada kondisi cuaca cerah. Sedangkan tidak ada yang menyewa sepeda pada cuaca buruk seperti saat badai atau hujan deras. Menariknya masih ada yang menyewa sepeda walaupun sedang hujan dan bersalju.
- Conclution pertanyaan 2: Pada grafik bar dapat disimpulkan bahwa lebih banyak yang menyewa sepeda saat hari kerja dibandingkan hari libur. Bisa disimpulkan bahwa penyewaan sepeda ini ditargetkan untuk pekerja atau siswa yang aktif pada hari kerja, bukan untuk liburan.
- Conclition pertanyaan 3: Perkembangan penyewaan sepeda dari tahun 2011 ke tahun 2012 adalah terjadi peningkatan yang signifikan pada tahun 2012. Dan menariknya pada akhir dan awal tahun terjadi penurunan yang cukup signifikan. Hal ini selaras dengan yang telah disimpulkan pada poin pertama dan ke 2 bahwa lebih banyak yang menyewa sepeda pada hari kerja, dikarenakan awal dan akhir tahun merupakan musim liburan dan cuacanya kurang bagus karena musim salju.
"""